modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersivePaintings/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "immersive_paintings"
version = "${version}"
displayName = "Immersive Paintings"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-paintings"
authors = "Luke100000"
description = "Use your own paintings!"
logoFile = "icon.png"
itemIcon = "immersive_paintings:painting"

[[dependencies.immersive_paintings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_paintings]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"
