plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

repositories {
    maven { url = "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Dependencies
    implementation("com.terraformersmc:modmenu:${modmenu_version}")
    implementation("me.fzzyhmstrs:fzzy_config:${fzzy_config_version}") {
        // Excluded because 0.7.0-SNAPSHOT doesn't exist as of this commit
        // It only impacts dev testing and shouldn't be an issue for a release
        exclude group: "me.lucko", module: "fabric-permissions-api"
    }

    // Third Party Dependencies
    include(implementation("com.twelvemonkeys.common:common-lang:${webp_version}"))
    include(implementation("com.twelvemonkeys.common:common-image:${webp_version}"))
    include(implementation("com.twelvemonkeys.imageio:imageio-core:${webp_version}"))
    include(implementation("com.twelvemonkeys.imageio:imageio-webp:${webp_version}"))
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}

sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}