plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom-remap' version '1.14-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.123' apply false
}

String getAppVersion() {
    try {
        def proc = "git tag --points-at HEAD".execute()
        def tag = proc.text.trim()
        if (tag.isEmpty()) return "0.0.1"
        return tag.split('\\+')[0]
    } catch (Exception e) {
        println "Warning: ${e.message}, is git installed?"
        return "0.0.1"
    }
}


subprojects {
    version = getAppVersion()
}
