plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.10-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.90' apply false
}

def getAppVersion = { ->
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'tag', '--points-at', 'HEAD'
            standardOutput = stdout
        }
        def tag = stdout.toString().trim()
        if (tag.isEmpty()) return "0.0.1"
        return tag.split('\\+')[0]
    } catch (Exception e) {
        println "Warning: ${e.message}, is git installed?"
        return "0.0.1"
    }
} as Object


subprojects {
    version = getAppVersion()
}