# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=net.conczin
java_version=25

# Config Options
mod_name=Immersive Paintings
mod_author=Luke100000
mod_id=immersive_paintings
license=GPL-3.0-only
credits=
description=Use your own paintings!
mod_homepage=https://conczin.net/
mod_sources=https://github.com/Luke100000/immersivePaintings
mod_issues=https://github.com/Luke100000/immersivePaintings/issues

# Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Loaders
# https://fabricmc.net/develop/
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.18.4

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.65-beta
neoforge_loader_version_range=[4,)

# Dependencies
fzzy_config_version=0.7.6+26.1
modmenu_version=18.0.0-alpha.8

# Third-Party Dependencies
webp_version=3.13.0
