# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=net.conczin
java_version=21

# Config Options
mod_name=Immersive Paintings
mod_author=Luke100000
mod_id=immersive_paintings
license=GPL-3.0-only
credits=
description=Use your own paintings!
mod_homepage=https://conczin.net/
mod_sources=https://github.com/Luke100000/immersivePaintings
mod_issues=https://github.com/Luke100000/immersivePaintings/issues

# Minecraft
minecraft_version=1.21.8
minecraft_version_range=[1.21.8, 1.21.9)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.8
parchment_version=2025.09.14

# Loaders
fabric_version=0.136.1+1.21.8
fabric_loader_version=0.18.4
neoforge_version=21.8.52
neoforge_loader_version_range=[4,)
#forge_version=52.1.0
#forge_loader_version_range=[52,)

# Dependencies
fzzy_config_version_neo=0.7.4+1.21.7
fzzy_config_version_fabric=0.7.4-fix1+1.21.6
modmenu_version=15.0.1

# Third-Party Dependencies
webp_version=3.13.0
