# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=net.conczin
java_version=21

# Config Options
mod_name=Immersive Paintings
mod_author=Luke100000
mod_id=immersive_paintings
license=GPL-3.0-only
credits=
description=Use your own paintings!
mod_homepage=https://conczin.net/
mod_sources=https://github.com/Luke100000/immersivePaintings
mod_issues=https://github.com/Luke100000/immersivePaintings/issues

# Minecraft
minecraft_version=1.21.11
minecraft_version_range=[1.21.11, 1.21.12)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Loaders
# https://fabricmc.net/develop/
fabric_version=0.141.1+1.21.11
fabric_loader_version=0.18.4
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.11.36-beta
neoforge_loader_version_range=[4,)
#forge_version=52.1.0
#forge_loader_version_range=[52,)

# Dependencies
fzzy_config_version=0.7.5+1.21.11
modmenu_version=17.0.0-beta.2

# Third-Party Dependencies
webp_version=3.13.0
