plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    maven { url = "https://thedarkcolour.github.io/KotlinForForge/" }
}

neoForge {
    version = neoforge_version

    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric

            def dir = project.getLayout().getProjectDirectory().dir('runs/' + it.name)
            if (!dir.asFile.exists()) {
                dir.asFile.mkdir()
            }
            getGameDirectory().convention(dir)
        }
        client {
            client()
        }
        // data {
        //     data()
        // }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "me.fzzyhmstrs:fzzy_config:${fzzy_config_version}+neoforge"

    jarJar(implementation("com.twelvemonkeys.common:common-lang:${webp_version}"))
    jarJar(implementation("com.twelvemonkeys.common:common-image:${webp_version}"))
    jarJar(implementation("com.twelvemonkeys.imageio:imageio-core:${webp_version}"))
    jarJar(implementation("com.twelvemonkeys.imageio:imageio-webp:${webp_version}"))
}
